version: '3.4'

services:
  app:
    build:
      context: .
    container_name: fin_web
    depends_on:
      - database
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development
  database:
    image: postgres:12.1
    container_name: fin_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  gem_cache:
  db_data:
