default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_financial_assistant_development

  username: <%= Rails.application.credentials.database[:pg_dev_user] if Rails.application.credentials.database %>
  password: <%= Rails.application.credentials.database[:pg_dev_pass] if Rails.application.credentials.database %>
  host: localhost

test:
  <<: *default
  database: my_financial_assistant_test

  username: <%= Rails.application.credentials.database[:pg_dev_user] if Rails.application.credentials.database %>
  password: <%= Rails.application.credentials.database[:pg_dev_pass] if Rails.application.credentials.database %>
  host: localhost

production:
  <<: *default
  database: my_financial_assistant_production
  username: my_financial_assistant
  password: <%= ENV['MY_FINANCIAL_ASSISTANT_DATABASE_PASSWORD'] %>
